### ISSUE TITLE
Let's revive Simplenews for Backdrop!

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/simplenews#1]
Hi Andy,

Recently, our team began porting the Simplenews module to Backdrop CMS. Unfortunately, we didn’t check for any prior efforts beforehand. This assumption came from discussions I came across on [Gitter](https://gitter.im/backdrop/backdrop-issues), which indicated a community need for Simplenews.

After completing and publishing our port on [GitHub](https://github.com/altagrade/simplenews), I was pleasantly surprised to discover that Simplenews had already been initiated on [Backdrop Contrib](https://github.com/backdrop-contrib/simplenews) — I think it’s fantastic that others are also working toward bringing this module to Backdrop CMS!

I noticed the README file mentions that the project is seeking maintainers. How about we join forces and co-maintain this project? I believe collaborating would not only save effort but also accelerate the progress of making Simplenews a robust solution for Backdrop users.

Let me know if you’re interested in reviving and maintaining Simplenews together. I look forward to hearing from you!

**Comment by quicksketch** [comment]
Thanks @alanmels, per https://github.com/backdrop-ops/contrib/issues/373 I've approved your request to maintain this module.

Because it looks like your port takes a different approach in some ways (the names of config variables for example), the port is not compatible with the current implementation. Had this module had a full (non-alpha) release, I would suggest making a version 2.0 instead. But as-is, your port taking over the 1.x namespace may be okay. I would encourage you to write an upgrade path if possible though for existing users.

Thanks @biolithic for initially creating this module. I hope you'll approve of the work @alanmels and other contributors provide for this module in the future.

**Comment by alanmels** [comment]
@quicksketch, Thank you for your review and approval of my request. 

Nice idea for upgrade path. Unfortunately, at the moment the hands of our team are tied up to current tasks queue on AltaGrade. However, if somebody in posterity will hit issues with upgrade we will help them or quickly write up the upgrade path.

@biolithic, you are more than welcome to join in as co-maintainer of the module any time.
