### ISSUE TITLE
Subscription categories on user admin form - placement in a vertical tab

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/simplenews#25]
I'm adding Simplenews to a site and have several newsletter categories planned. I've just added it and want to be able to subscribe (or not) to the different categories. The subscription categories have been added to the user admin form as shown here, in a fieldset before the vertical tabs of other field groups:

![image](https://github.com/backdrop-contrib/simplenews/assets/54537636/7b565771-a63d-4457-a3df-e67cb8a4246f)

How can I make this appear in a vertical tab? Is this just me, or do others see this same issue?

**Comment by olafgrabienski** [comment]
> Is this just me, or do others see this same issue?

I see the same.

**Comment by nattywebdev** [comment]
Thanks for confirming Olaf - so this is because I've chosen to integrate with the user accounts, but there's no formatting defined that allows this to be seen as other fields, in vertical tabs.
Would that be a feature request, or an error report?

**Comment by olafgrabienski** [comment]
The Simplenews module was ported before the introduction of vertical tabs on the user account form (see https://github.com/backdrop/backdrop-issues/issues/3872). With this change, the subscription categories should be moved a vertical tab, in my opinion, because vertival tabs are the new way how Backdrop organizes the form. I wouldn't call it an "error", though, more something like a "task".

**Comment by alanmels** [comment]
Right, as @olafgrabienski explained, the Simplenews module was ported from Drupal 7 as is. I'll consider moving the Simplenews setting options to vertical tabs when I have time, until then anyone is welcome to file PRs for this issue.

**Comment by nattywebdev** [comment]
Fantastic - thank you @alanmels
